apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 252536270780.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 252536270780.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e247f6ab
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
